# Generated by Django 3.2.25 on 2025-06-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pruducts',
            new_name='Product',
        ),
    ]
